dist: trusty
language: php

php:
  - "nightly"
  - "7.1"
  - "7.0"
  - "5.6"
  - "hhvm"

matrix:
  allow_failures:
    - php: "hhvm"
    - php: "nightly"
      env: DOKUWIKI=stable
    - php: "7.1"
      env: DOKUWIKI=stable

env:
  - DOKUWIKI=master
  - DOKUWIKI=stable

before_install:
  - wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh

install:
  - sh travis.sh

script:
  - cd _test && PRESERVE_TMP=false phpunit --stderr --group plugin_backlinks --verbose --debug
